version: '3.8'

services:
  app:
    build: .
    ports:
      - "8000:8000"
    environment:
      - DB_HOST=db
      - DB_USER=root
      - DB_PASSWORD=yourpassword
      - DB_NAME=dz_tabib
      - DB_TEST_NAME=dz_tabib_test
      - JWT_SECRET_KEY=your_secret_key
      - JWT_ALGORITHM=HS256
      - ACCESS_TOKEN_EXPIRE_MINUTES=60
      - MAIL_USERNAME=dztabibapp@gmail.com
      - MAIL_PASSWORD=jzrr kcfy qwql lpds
      - MAIL_SERVER=smtp.gmail.com
      - MAIL_PORT=587
      - MAIL_FROM=dztabibapp@gmail.com
      - MAIL_FROM_NAME=DZ-TABIB
    depends_on:
      - db

  db:
    image: mysql:5.7
    environment:
      MYSQL_ROOT_PASSWORD: yourpassword
      MYSQL_DATABASE: dz_tabib
      MYSQL_USER: root
      MYSQL_PASSWORD: yourpassword
    ports:
      - "3306:3306"
    volumes:
      - db_data:/var/lib/mysql

volumes:
  db_data: